In [9]:
import tensorflow  
import numpy as np
from numpy import linalg
from numpy.linalg import norm
from tensorflow import keras 
import os 
from tqdm import tqdm
from tensorflow.keras.preprocessing import image 
from tensorflow.keras.layers import GlobalMaxPool2D
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input

model = ResNet50(weights= "imagenet", include_top= False, input_shape=(224, 224, 3))
model.trainable = False

model = tensorflow.keras.Sequential([

    model, 
    GlobalMaxPool2D()

])
#print(model.summary())

In [15]:
def extract_features(image_path , model):
    img = image.load_img(image_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    exp_img_array = np.expand_dims(img_array, axis = 0)
    preprocessed_img = preprocess_input(exp_img_array)
    results = model.predict(preprocessed_img).flatten()
    normalized_results = results/norm(results)
    return normalized_results

print

filename = []
for file in os.listdir("images"):
    filename.append(os.path.join("images", file))

#print(os.listdir("images"))

features_list = []
for file_path in tqdm(filename):
    features_list.append(extract_features(file_path, model))
features_list = np.array(features_list)
print(features_list)







2023-10-28 14:03:27.982104: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 29ms/step
[[0.00684079 0.03663964 0.01238347 ... 0.01264841 0.         0.02691427]
 [0.00243908 0.00502098 0.         ... 0.00899791 0.01014097 0.020117  ]
 [0.00300273 0.02200999 0.00272648 ... 0.01291527 0.0161933  0.03272966]
 ...
 [0.00863952 0.00114747 0.01275451 ... 0.0092804  0.00524168 0.01923628]
 [0.01022248 0.02715308 0.00925248 ... 0.         0.01292528 0.03180479]
 [0.         0.00010638 0.01402253 ... 0.01400297 0.02283377 0.00238573]]


In [17]:
print(features_list.shape)

(44441, 2048)


In [19]:
import pickle
pickle.dump(features_list, open("embeding.pkl", "wb"))
pickle.dump(filename, open("filename.pkl", "wb"))